// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xudrpc.proto

/*
Package xudrpc is a generated protocol buffer package.

It is generated from these files:
	xudrpc.proto

It has these top-level messages:
	AddCurrencyRequest
	AddCurrencyResponse
	AddPairRequest
	AddPairResponse
	RemoveOrderRequest
	RemoveOrderResponse
	ChannelBalance
	ChannelBalanceRequest
	ChannelBalanceResponse
	ConnectRequest
	ConnectResponse
	BanRequest
	BanResponse
	GetInfoRequest
	GetInfoResponse
	GetOrdersRequest
	GetOrdersResponse
	ListCurrenciesRequest
	ListCurrenciesResponse
	ListPairsRequest
	ListPairsResponse
	ListPeersRequest
	ListPeersResponse
	LndChannels
	LndInfo
	Order
	OrderRemoval
	Orders
	OrderMatch
	OrdersCount
	Peer
	PlaceOrderRequest
	PlaceOrderResponse
	RaidenInfo
	RemoveCurrencyRequest
	RemoveCurrencyResponse
	RemovePairRequest
	RemovePairResponse
	ShutdownRequest
	ShutdownResponse
	SubscribeAddedOrdersRequest
	SubscribeRemovedOrdersRequest
	SubscribeSwapsRequest
	SwapResult
*/
package xudrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OrderSide int32

const (
	OrderSide_BUY  OrderSide = 0
	OrderSide_SELL OrderSide = 1
)

var OrderSide_name = map[int32]string{
	0: "BUY",
	1: "SELL",
}
var OrderSide_value = map[string]int32{
	"BUY":  0,
	"SELL": 1,
}

func (x OrderSide) String() string {
	return proto.EnumName(OrderSide_name, int32(x))
}
func (OrderSide) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type AddCurrencyRequest_SwapClient int32

const (
	AddCurrencyRequest_LND    AddCurrencyRequest_SwapClient = 0
	AddCurrencyRequest_RAIDEN AddCurrencyRequest_SwapClient = 1
)

var AddCurrencyRequest_SwapClient_name = map[int32]string{
	0: "LND",
	1: "RAIDEN",
}
var AddCurrencyRequest_SwapClient_value = map[string]int32{
	"LND":    0,
	"RAIDEN": 1,
}

func (x AddCurrencyRequest_SwapClient) String() string {
	return proto.EnumName(AddCurrencyRequest_SwapClient_name, int32(x))
}
func (AddCurrencyRequest_SwapClient) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type SwapResult_Role int32

const (
	SwapResult_TAKER SwapResult_Role = 0
	SwapResult_MAKER SwapResult_Role = 1
)

var SwapResult_Role_name = map[int32]string{
	0: "TAKER",
	1: "MAKER",
}
var SwapResult_Role_value = map[string]int32{
	"TAKER": 0,
	"MAKER": 1,
}

func (x SwapResult_Role) String() string {
	return proto.EnumName(SwapResult_Role_name, int32(x))
}
func (SwapResult_Role) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{43, 0} }

type AddCurrencyRequest struct {
	// The ticker symbol for this currency such as BTC, LTC, ETH, etc...
	Currency string `protobuf:"bytes,1,opt,name=currency" json:"currency,omitempty"`
	// The payment channel network client to use for executing swaps
	SwapClient AddCurrencyRequest_SwapClient `protobuf:"varint,2,opt,name=swap_client,enum=xudrpc.AddCurrencyRequest_SwapClient" json:"swap_client,omitempty"`
	// The contract address for layered tokens such as ERC20
	TokenAddress string `protobuf:"bytes,3,opt,name=token_address" json:"token_address,omitempty"`
	// The number of places to the right of the decimal point of the smallest subunit of the currency. For example, BTC, LTC, and others
	// where the smallest subunits (satoshis) are 0.00000001 full units (bitcoins) have 8 decimal places. ETH has 18. This can be thought
	// of as the base 10 exponent of the smallest subunit expressed as a positive integer. A default value of 8 is used if unspecified.
	DecimalPlaces uint32 `protobuf:"varint,4,opt,name=decimal_places" json:"decimal_places,omitempty"`
}

func (m *AddCurrencyRequest) Reset()                    { *m = AddCurrencyRequest{} }
func (m *AddCurrencyRequest) String() string            { return proto.CompactTextString(m) }
func (*AddCurrencyRequest) ProtoMessage()               {}
func (*AddCurrencyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddCurrencyRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *AddCurrencyRequest) GetSwapClient() AddCurrencyRequest_SwapClient {
	if m != nil {
		return m.SwapClient
	}
	return AddCurrencyRequest_LND
}

func (m *AddCurrencyRequest) GetTokenAddress() string {
	if m != nil {
		return m.TokenAddress
	}
	return ""
}

func (m *AddCurrencyRequest) GetDecimalPlaces() uint32 {
	if m != nil {
		return m.DecimalPlaces
	}
	return 0
}

type AddCurrencyResponse struct {
}

func (m *AddCurrencyResponse) Reset()                    { *m = AddCurrencyResponse{} }
func (m *AddCurrencyResponse) String() string            { return proto.CompactTextString(m) }
func (*AddCurrencyResponse) ProtoMessage()               {}
func (*AddCurrencyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type AddPairRequest struct {
	// The base currency that is bought and sold for this trading pair
	BaseCurrency string `protobuf:"bytes,1,opt,name=base_currency" json:"base_currency,omitempty"`
	// The currency used to quote a price for the base currency
	QuoteCurrency string `protobuf:"bytes,2,opt,name=quote_currency" json:"quote_currency,omitempty"`
}

func (m *AddPairRequest) Reset()                    { *m = AddPairRequest{} }
func (m *AddPairRequest) String() string            { return proto.CompactTextString(m) }
func (*AddPairRequest) ProtoMessage()               {}
func (*AddPairRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddPairRequest) GetBaseCurrency() string {
	if m != nil {
		return m.BaseCurrency
	}
	return ""
}

func (m *AddPairRequest) GetQuoteCurrency() string {
	if m != nil {
		return m.QuoteCurrency
	}
	return ""
}

type AddPairResponse struct {
}

func (m *AddPairResponse) Reset()                    { *m = AddPairResponse{} }
func (m *AddPairResponse) String() string            { return proto.CompactTextString(m) }
func (*AddPairResponse) ProtoMessage()               {}
func (*AddPairResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RemoveOrderRequest struct {
	// The local id of the order to remove
	OrderId string `protobuf:"bytes,1,opt,name=order_id" json:"order_id,omitempty"`
}

func (m *RemoveOrderRequest) Reset()                    { *m = RemoveOrderRequest{} }
func (m *RemoveOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveOrderRequest) ProtoMessage()               {}
func (*RemoveOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RemoveOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type RemoveOrderResponse struct {
}

func (m *RemoveOrderResponse) Reset()                    { *m = RemoveOrderResponse{} }
func (m *RemoveOrderResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveOrderResponse) ProtoMessage()               {}
func (*RemoveOrderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ChannelBalance struct {
	// Sum of channels balances denominated in satoshis or equivalent
	Balance int64 `protobuf:"varint,1,opt,name=balance" json:"balance,omitempty"`
	// Sum of channels pending balances denominated in satoshis or equivalent
	PendingOpenBalance int64 `protobuf:"varint,2,opt,name=pending_open_balance" json:"pending_open_balance,omitempty"`
}

func (m *ChannelBalance) Reset()                    { *m = ChannelBalance{} }
func (m *ChannelBalance) String() string            { return proto.CompactTextString(m) }
func (*ChannelBalance) ProtoMessage()               {}
func (*ChannelBalance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ChannelBalance) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *ChannelBalance) GetPendingOpenBalance() int64 {
	if m != nil {
		return m.PendingOpenBalance
	}
	return 0
}

type ChannelBalanceRequest struct {
	// The ticker symbol of the currency to query for, if unspecified then balances for all
	// supported currencies are queried
	Currency string `protobuf:"bytes,1,opt,name=currency" json:"currency,omitempty"`
}

func (m *ChannelBalanceRequest) Reset()                    { *m = ChannelBalanceRequest{} }
func (m *ChannelBalanceRequest) String() string            { return proto.CompactTextString(m) }
func (*ChannelBalanceRequest) ProtoMessage()               {}
func (*ChannelBalanceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ChannelBalanceRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type ChannelBalanceResponse struct {
	// A map between currency ticker symbols and their channel balances
	Balances map[string]*ChannelBalance `protobuf:"bytes,1,rep,name=balances,json=orders" json:"balances,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ChannelBalanceResponse) Reset()                    { *m = ChannelBalanceResponse{} }
func (m *ChannelBalanceResponse) String() string            { return proto.CompactTextString(m) }
func (*ChannelBalanceResponse) ProtoMessage()               {}
func (*ChannelBalanceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ChannelBalanceResponse) GetBalances() map[string]*ChannelBalance {
	if m != nil {
		return m.Balances
	}
	return nil
}

type ConnectRequest struct {
	NodeUri string `protobuf:"bytes,1,opt,name=node_uri" json:"node_uri,omitempty"`
}

func (m *ConnectRequest) Reset()                    { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string            { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()               {}
func (*ConnectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ConnectRequest) GetNodeUri() string {
	if m != nil {
		return m.NodeUri
	}
	return ""
}

type ConnectResponse struct {
}

func (m *ConnectResponse) Reset()                    { *m = ConnectResponse{} }
func (m *ConnectResponse) String() string            { return proto.CompactTextString(m) }
func (*ConnectResponse) ProtoMessage()               {}
func (*ConnectResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type BanRequest struct {
	NodePubKey string `protobuf:"bytes,1,opt,name=node_pub_key" json:"node_pub_key,omitempty"`
}

func (m *BanRequest) Reset()                    { *m = BanRequest{} }
func (m *BanRequest) String() string            { return proto.CompactTextString(m) }
func (*BanRequest) ProtoMessage()               {}
func (*BanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *BanRequest) GetNodePubKey() string {
	if m != nil {
		return m.NodePubKey
	}
	return ""
}

type BanResponse struct {
}

func (m *BanResponse) Reset()                    { *m = BanResponse{} }
func (m *BanResponse) String() string            { return proto.CompactTextString(m) }
func (*BanResponse) ProtoMessage()               {}
func (*BanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type GetInfoRequest struct {
}

func (m *GetInfoRequest) Reset()                    { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()               {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type GetInfoResponse struct {
	Version    string       `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	NodePubKey string       `protobuf:"bytes,2,opt,name=node_pub_key" json:"node_pub_key,omitempty"`
	Uris       []string     `protobuf:"bytes,3,rep,name=uris" json:"uris,omitempty"`
	NumPeers   int32        `protobuf:"varint,4,opt,name=num_peers" json:"num_peers,omitempty"`
	NumPairs   int32        `protobuf:"varint,5,opt,name=num_pairs" json:"num_pairs,omitempty"`
	Orders     *OrdersCount `protobuf:"bytes,6,opt,name=orders" json:"orders,omitempty"`
	Lndbtc     *LndInfo     `protobuf:"bytes,7,opt,name=lndbtc" json:"lndbtc,omitempty"`
	Lndltc     *LndInfo     `protobuf:"bytes,8,opt,name=lndltc" json:"lndltc,omitempty"`
	Raiden     *RaidenInfo  `protobuf:"bytes,9,opt,name=raiden" json:"raiden,omitempty"`
}

func (m *GetInfoResponse) Reset()                    { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()               {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetInfoResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetInfoResponse) GetNodePubKey() string {
	if m != nil {
		return m.NodePubKey
	}
	return ""
}

func (m *GetInfoResponse) GetUris() []string {
	if m != nil {
		return m.Uris
	}
	return nil
}

func (m *GetInfoResponse) GetNumPeers() int32 {
	if m != nil {
		return m.NumPeers
	}
	return 0
}

func (m *GetInfoResponse) GetNumPairs() int32 {
	if m != nil {
		return m.NumPairs
	}
	return 0
}

func (m *GetInfoResponse) GetOrders() *OrdersCount {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *GetInfoResponse) GetLndbtc() *LndInfo {
	if m != nil {
		return m.Lndbtc
	}
	return nil
}

func (m *GetInfoResponse) GetLndltc() *LndInfo {
	if m != nil {
		return m.Lndltc
	}
	return nil
}

func (m *GetInfoResponse) GetRaiden() *RaidenInfo {
	if m != nil {
		return m.Raiden
	}
	return nil
}

type GetOrdersRequest struct {
	// The trading pair for which to retrieve orders
	PairId string `protobuf:"bytes,1,opt,name=pair_id" json:"pair_id,omitempty"`
	// Whether own orders should be included in result or not
	IncludeOwnOrders bool `protobuf:"varint,2,opt,name=include_own_orders" json:"include_own_orders,omitempty"`
}

func (m *GetOrdersRequest) Reset()                    { *m = GetOrdersRequest{} }
func (m *GetOrdersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetOrdersRequest) ProtoMessage()               {}
func (*GetOrdersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *GetOrdersRequest) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *GetOrdersRequest) GetIncludeOwnOrders() bool {
	if m != nil {
		return m.IncludeOwnOrders
	}
	return false
}

type GetOrdersResponse struct {
	// A map between pair ids and their buy and sell orders
	Orders map[string]*Orders `protobuf:"bytes,1,rep,name=orders" json:"orders,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *GetOrdersResponse) Reset()                    { *m = GetOrdersResponse{} }
func (m *GetOrdersResponse) String() string            { return proto.CompactTextString(m) }
func (*GetOrdersResponse) ProtoMessage()               {}
func (*GetOrdersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GetOrdersResponse) GetOrders() map[string]*Orders {
	if m != nil {
		return m.Orders
	}
	return nil
}

type ListCurrenciesRequest struct {
}

func (m *ListCurrenciesRequest) Reset()                    { *m = ListCurrenciesRequest{} }
func (m *ListCurrenciesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListCurrenciesRequest) ProtoMessage()               {}
func (*ListCurrenciesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type ListCurrenciesResponse struct {
	// The ticker symbols of supported currencies
	Currencies []string `protobuf:"bytes,1,rep,name=currencies" json:"currencies,omitempty"`
}

func (m *ListCurrenciesResponse) Reset()                    { *m = ListCurrenciesResponse{} }
func (m *ListCurrenciesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListCurrenciesResponse) ProtoMessage()               {}
func (*ListCurrenciesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ListCurrenciesResponse) GetCurrencies() []string {
	if m != nil {
		return m.Currencies
	}
	return nil
}

type ListPairsRequest struct {
}

func (m *ListPairsRequest) Reset()                    { *m = ListPairsRequest{} }
func (m *ListPairsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListPairsRequest) ProtoMessage()               {}
func (*ListPairsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type ListPairsResponse struct {
	// The supported trading pair tickers in formats like "LTC/BTC"
	Pairs []string `protobuf:"bytes,1,rep,name=pairs" json:"pairs,omitempty"`
}

func (m *ListPairsResponse) Reset()                    { *m = ListPairsResponse{} }
func (m *ListPairsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListPairsResponse) ProtoMessage()               {}
func (*ListPairsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ListPairsResponse) GetPairs() []string {
	if m != nil {
		return m.Pairs
	}
	return nil
}

type ListPeersRequest struct {
}

func (m *ListPeersRequest) Reset()                    { *m = ListPeersRequest{} }
func (m *ListPeersRequest) String() string            { return proto.CompactTextString(m) }
func (*ListPeersRequest) ProtoMessage()               {}
func (*ListPeersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type ListPeersResponse struct {
	Peers []*Peer `protobuf:"bytes,1,rep,name=peers" json:"peers,omitempty"`
}

func (m *ListPeersResponse) Reset()                    { *m = ListPeersResponse{} }
func (m *ListPeersResponse) String() string            { return proto.CompactTextString(m) }
func (*ListPeersResponse) ProtoMessage()               {}
func (*ListPeersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ListPeersResponse) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type LndChannels struct {
	Active   int32 `protobuf:"varint,1,opt,name=active" json:"active,omitempty"`
	Inactive int32 `protobuf:"varint,2,opt,name=inactive" json:"inactive,omitempty"`
	Pending  int32 `protobuf:"varint,3,opt,name=pending" json:"pending,omitempty"`
}

func (m *LndChannels) Reset()                    { *m = LndChannels{} }
func (m *LndChannels) String() string            { return proto.CompactTextString(m) }
func (*LndChannels) ProtoMessage()               {}
func (*LndChannels) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *LndChannels) GetActive() int32 {
	if m != nil {
		return m.Active
	}
	return 0
}

func (m *LndChannels) GetInactive() int32 {
	if m != nil {
		return m.Inactive
	}
	return 0
}

func (m *LndChannels) GetPending() int32 {
	if m != nil {
		return m.Pending
	}
	return 0
}

type LndInfo struct {
	Error       string       `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Channels    *LndChannels `protobuf:"bytes,2,opt,name=channels" json:"channels,omitempty"`
	Chains      []string     `protobuf:"bytes,3,rep,name=chains" json:"chains,omitempty"`
	Blockheight int32        `protobuf:"varint,4,opt,name=blockheight" json:"blockheight,omitempty"`
	Uris        []string     `protobuf:"bytes,5,rep,name=uris" json:"uris,omitempty"`
	Version     string       `protobuf:"bytes,6,opt,name=version" json:"version,omitempty"`
	Alias       string       `protobuf:"bytes,7,opt,name=alias" json:"alias,omitempty"`
}

func (m *LndInfo) Reset()                    { *m = LndInfo{} }
func (m *LndInfo) String() string            { return proto.CompactTextString(m) }
func (*LndInfo) ProtoMessage()               {}
func (*LndInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *LndInfo) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *LndInfo) GetChannels() *LndChannels {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *LndInfo) GetChains() []string {
	if m != nil {
		return m.Chains
	}
	return nil
}

func (m *LndInfo) GetBlockheight() int32 {
	if m != nil {
		return m.Blockheight
	}
	return 0
}

func (m *LndInfo) GetUris() []string {
	if m != nil {
		return m.Uris
	}
	return nil
}

func (m *LndInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *LndInfo) GetAlias() string {
	if m != nil {
		return m.Alias
	}
	return ""
}

type Order struct {
	// The price of the order.
	Price float64 `protobuf:"fixed64,1,opt,name=price" json:"price,omitempty"`
	// The quantity of the order.
	Quantity float64 `protobuf:"fixed64,2,opt,name=quantity" json:"quantity,omitempty"`
	// The trading pair that this order is for.
	PairId string `protobuf:"bytes,3,opt,name=pair_id" json:"pair_id,omitempty"`
	// A UUID for this order.
	Id string `protobuf:"bytes,4,opt,name=id" json:"id,omitempty"`
	// Types that are valid to be assigned to OwnOrPeer:
	//	*Order_PeerPubKey
	//	*Order_LocalId
	OwnOrPeer isOrder_OwnOrPeer `protobuf_oneof:"own_or_peer"`
	// The epoch time when this order was created.
	CreatedAt int64 `protobuf:"varint,7,opt,name=created_at" json:"created_at,omitempty"`
	// Whether this order is a buy or sell
	Side OrderSide `protobuf:"varint,8,opt,name=side,enum=xudrpc.OrderSide" json:"side,omitempty"`
	// Whether this order is a local own order or a remote peer order.
	IsOwnOrder bool `protobuf:"varint,9,opt,name=is_own_order" json:"is_own_order,omitempty"`
}

func (m *Order) Reset()                    { *m = Order{} }
func (m *Order) String() string            { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()               {}
func (*Order) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

type isOrder_OwnOrPeer interface{ isOrder_OwnOrPeer() }

type Order_PeerPubKey struct {
	PeerPubKey string `protobuf:"bytes,5,opt,name=peer_pub_key,oneof"`
}
type Order_LocalId struct {
	LocalId string `protobuf:"bytes,6,opt,name=local_id,oneof"`
}

func (*Order_PeerPubKey) isOrder_OwnOrPeer() {}
func (*Order_LocalId) isOrder_OwnOrPeer()    {}

func (m *Order) GetOwnOrPeer() isOrder_OwnOrPeer {
	if m != nil {
		return m.OwnOrPeer
	}
	return nil
}

func (m *Order) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetQuantity() float64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Order) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetPeerPubKey() string {
	if x, ok := m.GetOwnOrPeer().(*Order_PeerPubKey); ok {
		return x.PeerPubKey
	}
	return ""
}

func (m *Order) GetLocalId() string {
	if x, ok := m.GetOwnOrPeer().(*Order_LocalId); ok {
		return x.LocalId
	}
	return ""
}

func (m *Order) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Order) GetSide() OrderSide {
	if m != nil {
		return m.Side
	}
	return OrderSide_BUY
}

func (m *Order) GetIsOwnOrder() bool {
	if m != nil {
		return m.IsOwnOrder
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Order) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Order_OneofMarshaler, _Order_OneofUnmarshaler, _Order_OneofSizer, []interface{}{
		(*Order_PeerPubKey)(nil),
		(*Order_LocalId)(nil),
	}
}

func _Order_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Order)
	// own_or_peer
	switch x := m.OwnOrPeer.(type) {
	case *Order_PeerPubKey:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.PeerPubKey)
	case *Order_LocalId:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.LocalId)
	case nil:
	default:
		return fmt.Errorf("Order.OwnOrPeer has unexpected type %T", x)
	}
	return nil
}

func _Order_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Order)
	switch tag {
	case 5: // own_or_peer.peer_pub_key
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OwnOrPeer = &Order_PeerPubKey{x}
		return true, err
	case 6: // own_or_peer.local_id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.OwnOrPeer = &Order_LocalId{x}
		return true, err
	default:
		return false, nil
	}
}

func _Order_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Order)
	// own_or_peer
	switch x := m.OwnOrPeer.(type) {
	case *Order_PeerPubKey:
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.PeerPubKey)))
		n += len(x.PeerPubKey)
	case *Order_LocalId:
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.LocalId)))
		n += len(x.LocalId)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type OrderRemoval struct {
	// The quantity of the order being removed.
	Quantity float64 `protobuf:"fixed64,1,opt,name=quantity" json:"quantity,omitempty"`
	// The trading pair that the order is for.
	PairId string `protobuf:"bytes,2,opt,name=pair_id" json:"pair_id,omitempty"`
	// The global UUID for the order.
	OrderId string `protobuf:"bytes,3,opt,name=order_id" json:"order_id,omitempty"`
	// The local id for the order, if applicable.
	LocalId string `protobuf:"bytes,4,opt,name=local_id" json:"local_id,omitempty"`
	// Whether the order being removed is a local own order or a remote peer order.
	IsOwnOrder bool `protobuf:"varint,5,opt,name=is_own_order" json:"is_own_order,omitempty"`
}

func (m *OrderRemoval) Reset()                    { *m = OrderRemoval{} }
func (m *OrderRemoval) String() string            { return proto.CompactTextString(m) }
func (*OrderRemoval) ProtoMessage()               {}
func (*OrderRemoval) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *OrderRemoval) GetQuantity() float64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *OrderRemoval) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *OrderRemoval) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderRemoval) GetLocalId() string {
	if m != nil {
		return m.LocalId
	}
	return ""
}

func (m *OrderRemoval) GetIsOwnOrder() bool {
	if m != nil {
		return m.IsOwnOrder
	}
	return false
}

type Orders struct {
	// A list of buy orders sorted by descending price
	BuyOrders []*Order `protobuf:"bytes,1,rep,name=buy_orders" json:"buy_orders,omitempty"`
	// A list of sell orders sorted by ascending price
	SellOrders []*Order `protobuf:"bytes,2,rep,name=sell_orders" json:"sell_orders,omitempty"`
}

func (m *Orders) Reset()                    { *m = Orders{} }
func (m *Orders) String() string            { return proto.CompactTextString(m) }
func (*Orders) ProtoMessage()               {}
func (*Orders) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *Orders) GetBuyOrders() []*Order {
	if m != nil {
		return m.BuyOrders
	}
	return nil
}

func (m *Orders) GetSellOrders() []*Order {
	if m != nil {
		return m.SellOrders
	}
	return nil
}

type OrderMatch struct {
	Maker *Order `protobuf:"bytes,1,opt,name=maker" json:"maker,omitempty"`
	Taker *Order `protobuf:"bytes,2,opt,name=taker" json:"taker,omitempty"`
}

func (m *OrderMatch) Reset()                    { *m = OrderMatch{} }
func (m *OrderMatch) String() string            { return proto.CompactTextString(m) }
func (*OrderMatch) ProtoMessage()               {}
func (*OrderMatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *OrderMatch) GetMaker() *Order {
	if m != nil {
		return m.Maker
	}
	return nil
}

func (m *OrderMatch) GetTaker() *Order {
	if m != nil {
		return m.Taker
	}
	return nil
}

type OrdersCount struct {
	Peer int32 `protobuf:"varint,1,opt,name=peer" json:"peer,omitempty"`
	Own  int32 `protobuf:"varint,2,opt,name=own" json:"own,omitempty"`
}

func (m *OrdersCount) Reset()                    { *m = OrdersCount{} }
func (m *OrdersCount) String() string            { return proto.CompactTextString(m) }
func (*OrdersCount) ProtoMessage()               {}
func (*OrdersCount) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *OrdersCount) GetPeer() int32 {
	if m != nil {
		return m.Peer
	}
	return 0
}

func (m *OrdersCount) GetOwn() int32 {
	if m != nil {
		return m.Own
	}
	return 0
}

type Peer struct {
	// The socket address with host and port for this peer
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	// The node pub key to uniquely identify this peer
	NodePubKey string `protobuf:"bytes,2,opt,name=node_pub_key" json:"node_pub_key,omitempty"`
	// The lnd BTC pub key associated with this peer
	LndBtcPubKey string `protobuf:"bytes,3,opt,name=lnd_btc_pub_key" json:"lnd_btc_pub_key,omitempty"`
	// The lnd LTC pub key associated with this peer
	LndLtcPubKey string `protobuf:"bytes,4,opt,name=lnd_ltc_pub_key" json:"lnd_ltc_pub_key,omitempty"`
	// Indicates whether this peer was connected inbound
	Inbound bool `protobuf:"varint,5,opt,name=inbound" json:"inbound,omitempty"`
	// A list of trading pair tickers supported by this peer
	Pairs []string `protobuf:"bytes,6,rep,name=pairs" json:"pairs,omitempty"`
	// The version of xud being used by the peer
	XudVersion string `protobuf:"bytes,7,opt,name=xud_version" json:"xud_version,omitempty"`
	// The time in seconds that we have been connected to this peer
	SecondsConnected int32 `protobuf:"varint,8,opt,name=seconds_connected" json:"seconds_connected,omitempty"`
}

func (m *Peer) Reset()                    { *m = Peer{} }
func (m *Peer) String() string            { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()               {}
func (*Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *Peer) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Peer) GetNodePubKey() string {
	if m != nil {
		return m.NodePubKey
	}
	return ""
}

func (m *Peer) GetLndBtcPubKey() string {
	if m != nil {
		return m.LndBtcPubKey
	}
	return ""
}

func (m *Peer) GetLndLtcPubKey() string {
	if m != nil {
		return m.LndLtcPubKey
	}
	return ""
}

func (m *Peer) GetInbound() bool {
	if m != nil {
		return m.Inbound
	}
	return false
}

func (m *Peer) GetPairs() []string {
	if m != nil {
		return m.Pairs
	}
	return nil
}

func (m *Peer) GetXudVersion() string {
	if m != nil {
		return m.XudVersion
	}
	return ""
}

func (m *Peer) GetSecondsConnected() int32 {
	if m != nil {
		return m.SecondsConnected
	}
	return 0
}

type PlaceOrderRequest struct {
	// The price of the order.
	Price float64 `protobuf:"fixed64,1,opt,name=price" json:"price,omitempty"`
	// The quantity of the order.
	Quantity float64 `protobuf:"fixed64,2,opt,name=quantity" json:"quantity,omitempty"`
	// The trading pair that the order is for
	PairId string `protobuf:"bytes,3,opt,name=pair_id" json:"pair_id,omitempty"`
	// The local id to assign to the order
	OrderId string `protobuf:"bytes,4,opt,name=order_id" json:"order_id,omitempty"`
	// Whether the order is a Buy or Sell
	Side OrderSide `protobuf:"varint,5,opt,name=side,enum=xudrpc.OrderSide" json:"side,omitempty"`
}

func (m *PlaceOrderRequest) Reset()                    { *m = PlaceOrderRequest{} }
func (m *PlaceOrderRequest) String() string            { return proto.CompactTextString(m) }
func (*PlaceOrderRequest) ProtoMessage()               {}
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *PlaceOrderRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PlaceOrderRequest) GetQuantity() float64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *PlaceOrderRequest) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *PlaceOrderRequest) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *PlaceOrderRequest) GetSide() OrderSide {
	if m != nil {
		return m.Side
	}
	return OrderSide_BUY
}

type PlaceOrderResponse struct {
	// A list of orders matching the newly placed order
	Matches []*OrderMatch `protobuf:"bytes,1,rep,name=matches" json:"matches,omitempty"`
	// The remaining portion of the order, after matches, that enters the order book
	RemainingOrder *Order `protobuf:"bytes,2,opt,name=remaining_order" json:"remaining_order,omitempty"`
}

func (m *PlaceOrderResponse) Reset()                    { *m = PlaceOrderResponse{} }
func (m *PlaceOrderResponse) String() string            { return proto.CompactTextString(m) }
func (*PlaceOrderResponse) ProtoMessage()               {}
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *PlaceOrderResponse) GetMatches() []*OrderMatch {
	if m != nil {
		return m.Matches
	}
	return nil
}

func (m *PlaceOrderResponse) GetRemainingOrder() *Order {
	if m != nil {
		return m.RemainingOrder
	}
	return nil
}

type RaidenInfo struct {
	Error    string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Address  string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Channels int32  `protobuf:"varint,3,opt,name=channels" json:"channels,omitempty"`
	Version  string `protobuf:"bytes,4,opt,name=version" json:"version,omitempty"`
}

func (m *RaidenInfo) Reset()                    { *m = RaidenInfo{} }
func (m *RaidenInfo) String() string            { return proto.CompactTextString(m) }
func (*RaidenInfo) ProtoMessage()               {}
func (*RaidenInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *RaidenInfo) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *RaidenInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RaidenInfo) GetChannels() int32 {
	if m != nil {
		return m.Channels
	}
	return 0
}

func (m *RaidenInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type RemoveCurrencyRequest struct {
	// The ticker symbol for this currency such as BTC, LTC, ETH, etc...
	Currency string `protobuf:"bytes,1,opt,name=currency" json:"currency,omitempty"`
}

func (m *RemoveCurrencyRequest) Reset()                    { *m = RemoveCurrencyRequest{} }
func (m *RemoveCurrencyRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveCurrencyRequest) ProtoMessage()               {}
func (*RemoveCurrencyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *RemoveCurrencyRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type RemoveCurrencyResponse struct {
}

func (m *RemoveCurrencyResponse) Reset()                    { *m = RemoveCurrencyResponse{} }
func (m *RemoveCurrencyResponse) String() string            { return proto.CompactTextString(m) }
func (*RemoveCurrencyResponse) ProtoMessage()               {}
func (*RemoveCurrencyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

type RemovePairRequest struct {
	// The trading pair ticker to remove, such as "LTC/BTC"
	PairId string `protobuf:"bytes,1,opt,name=pair_id" json:"pair_id,omitempty"`
}

func (m *RemovePairRequest) Reset()                    { *m = RemovePairRequest{} }
func (m *RemovePairRequest) String() string            { return proto.CompactTextString(m) }
func (*RemovePairRequest) ProtoMessage()               {}
func (*RemovePairRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *RemovePairRequest) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

type RemovePairResponse struct {
}

func (m *RemovePairResponse) Reset()                    { *m = RemovePairResponse{} }
func (m *RemovePairResponse) String() string            { return proto.CompactTextString(m) }
func (*RemovePairResponse) ProtoMessage()               {}
func (*RemovePairResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

type ShutdownRequest struct {
}

func (m *ShutdownRequest) Reset()                    { *m = ShutdownRequest{} }
func (m *ShutdownRequest) String() string            { return proto.CompactTextString(m) }
func (*ShutdownRequest) ProtoMessage()               {}
func (*ShutdownRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

type ShutdownResponse struct {
}

func (m *ShutdownResponse) Reset()                    { *m = ShutdownResponse{} }
func (m *ShutdownResponse) String() string            { return proto.CompactTextString(m) }
func (*ShutdownResponse) ProtoMessage()               {}
func (*ShutdownResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

type SubscribeAddedOrdersRequest struct {
}

func (m *SubscribeAddedOrdersRequest) Reset()                    { *m = SubscribeAddedOrdersRequest{} }
func (m *SubscribeAddedOrdersRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeAddedOrdersRequest) ProtoMessage()               {}
func (*SubscribeAddedOrdersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

type SubscribeRemovedOrdersRequest struct {
}

func (m *SubscribeRemovedOrdersRequest) Reset()                    { *m = SubscribeRemovedOrdersRequest{} }
func (m *SubscribeRemovedOrdersRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeRemovedOrdersRequest) ProtoMessage()               {}
func (*SubscribeRemovedOrdersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

type SubscribeSwapsRequest struct {
}

func (m *SubscribeSwapsRequest) Reset()                    { *m = SubscribeSwapsRequest{} }
func (m *SubscribeSwapsRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeSwapsRequest) ProtoMessage()               {}
func (*SubscribeSwapsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

type SwapResult struct {
	// The global UUID for the order that was swapped.
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId" json:"order_id,omitempty"`
	// The local id for the order that was swapped.
	LocalId string `protobuf:"bytes,2,opt,name=local_id" json:"local_id,omitempty"`
	// The trading pair that this order is for.
	PairId string `protobuf:"bytes,3,opt,name=pair_id" json:"pair_id,omitempty"`
	// The hex-encoded r_hash for the swap payments.
	RHash string `protobuf:"bytes,4,opt,name=r_hash" json:"r_hash,omitempty"`
	// The amount of subunits (satoshis) received.
	AmountReceived int64 `protobuf:"varint,5,opt,name=amount_received" json:"amount_received,omitempty"`
	// The amount of subunits (satoshis) sent.
	AmountSent int64 `protobuf:"varint,6,opt,name=amount_sent" json:"amount_sent,omitempty"`
	// The node pub key of the peer that executed this order.
	PeerPubKey string `protobuf:"bytes,7,opt,name=peer_pub_key" json:"peer_pub_key,omitempty"`
	// Our role in the swap, either MAKER or TAKER
	Role SwapResult_Role `protobuf:"varint,8,opt,name=role,enum=xudrpc.SwapResult_Role" json:"role,omitempty"`
}

func (m *SwapResult) Reset()                    { *m = SwapResult{} }
func (m *SwapResult) String() string            { return proto.CompactTextString(m) }
func (*SwapResult) ProtoMessage()               {}
func (*SwapResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *SwapResult) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *SwapResult) GetLocalId() string {
	if m != nil {
		return m.LocalId
	}
	return ""
}

func (m *SwapResult) GetPairId() string {
	if m != nil {
		return m.PairId
	}
	return ""
}

func (m *SwapResult) GetRHash() string {
	if m != nil {
		return m.RHash
	}
	return ""
}

func (m *SwapResult) GetAmountReceived() int64 {
	if m != nil {
		return m.AmountReceived
	}
	return 0
}

func (m *SwapResult) GetAmountSent() int64 {
	if m != nil {
		return m.AmountSent
	}
	return 0
}

func (m *SwapResult) GetPeerPubKey() string {
	if m != nil {
		return m.PeerPubKey
	}
	return ""
}

func (m *SwapResult) GetRole() SwapResult_Role {
	if m != nil {
		return m.Role
	}
	return SwapResult_TAKER
}

func init() {
	proto.RegisterType((*AddCurrencyRequest)(nil), "xudrpc.AddCurrencyRequest")
	proto.RegisterType((*AddCurrencyResponse)(nil), "xudrpc.AddCurrencyResponse")
	proto.RegisterType((*AddPairRequest)(nil), "xudrpc.AddPairRequest")
	proto.RegisterType((*AddPairResponse)(nil), "xudrpc.AddPairResponse")
	proto.RegisterType((*RemoveOrderRequest)(nil), "xudrpc.RemoveOrderRequest")
	proto.RegisterType((*RemoveOrderResponse)(nil), "xudrpc.RemoveOrderResponse")
	proto.RegisterType((*ChannelBalance)(nil), "xudrpc.ChannelBalance")
	proto.RegisterType((*ChannelBalanceRequest)(nil), "xudrpc.ChannelBalanceRequest")
	proto.RegisterType((*ChannelBalanceResponse)(nil), "xudrpc.ChannelBalanceResponse")
	proto.RegisterType((*ConnectRequest)(nil), "xudrpc.ConnectRequest")
	proto.RegisterType((*ConnectResponse)(nil), "xudrpc.ConnectResponse")
	proto.RegisterType((*BanRequest)(nil), "xudrpc.BanRequest")
	proto.RegisterType((*BanResponse)(nil), "xudrpc.BanResponse")
	proto.RegisterType((*GetInfoRequest)(nil), "xudrpc.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "xudrpc.GetInfoResponse")
	proto.RegisterType((*GetOrdersRequest)(nil), "xudrpc.GetOrdersRequest")
	proto.RegisterType((*GetOrdersResponse)(nil), "xudrpc.GetOrdersResponse")
	proto.RegisterType((*ListCurrenciesRequest)(nil), "xudrpc.ListCurrenciesRequest")
	proto.RegisterType((*ListCurrenciesResponse)(nil), "xudrpc.ListCurrenciesResponse")
	proto.RegisterType((*ListPairsRequest)(nil), "xudrpc.ListPairsRequest")
	proto.RegisterType((*ListPairsResponse)(nil), "xudrpc.ListPairsResponse")
	proto.RegisterType((*ListPeersRequest)(nil), "xudrpc.ListPeersRequest")
	proto.RegisterType((*ListPeersResponse)(nil), "xudrpc.ListPeersResponse")
	proto.RegisterType((*LndChannels)(nil), "xudrpc.LndChannels")
	proto.RegisterType((*LndInfo)(nil), "xudrpc.LndInfo")
	proto.RegisterType((*Order)(nil), "xudrpc.Order")
	proto.RegisterType((*OrderRemoval)(nil), "xudrpc.OrderRemoval")
	proto.RegisterType((*Orders)(nil), "xudrpc.Orders")
	proto.RegisterType((*OrderMatch)(nil), "xudrpc.OrderMatch")
	proto.RegisterType((*OrdersCount)(nil), "xudrpc.OrdersCount")
	proto.RegisterType((*Peer)(nil), "xudrpc.Peer")
	proto.RegisterType((*PlaceOrderRequest)(nil), "xudrpc.PlaceOrderRequest")
	proto.RegisterType((*PlaceOrderResponse)(nil), "xudrpc.PlaceOrderResponse")
	proto.RegisterType((*RaidenInfo)(nil), "xudrpc.RaidenInfo")
	proto.RegisterType((*RemoveCurrencyRequest)(nil), "xudrpc.RemoveCurrencyRequest")
	proto.RegisterType((*RemoveCurrencyResponse)(nil), "xudrpc.RemoveCurrencyResponse")
	proto.RegisterType((*RemovePairRequest)(nil), "xudrpc.RemovePairRequest")
	proto.RegisterType((*RemovePairResponse)(nil), "xudrpc.RemovePairResponse")
	proto.RegisterType((*ShutdownRequest)(nil), "xudrpc.ShutdownRequest")
	proto.RegisterType((*ShutdownResponse)(nil), "xudrpc.ShutdownResponse")
	proto.RegisterType((*SubscribeAddedOrdersRequest)(nil), "xudrpc.SubscribeAddedOrdersRequest")
	proto.RegisterType((*SubscribeRemovedOrdersRequest)(nil), "xudrpc.SubscribeRemovedOrdersRequest")
	proto.RegisterType((*SubscribeSwapsRequest)(nil), "xudrpc.SubscribeSwapsRequest")
	proto.RegisterType((*SwapResult)(nil), "xudrpc.SwapResult")
	proto.RegisterEnum("xudrpc.OrderSide", OrderSide_name, OrderSide_value)
	proto.RegisterEnum("xudrpc.AddCurrencyRequest_SwapClient", AddCurrencyRequest_SwapClient_name, AddCurrencyRequest_SwapClient_value)
	proto.RegisterEnum("xudrpc.SwapResult_Role", SwapResult_Role_name, SwapResult_Role_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Xud service

type XudClient interface {
	// Add a currency to the list of supported currencies.
	AddCurrency(ctx context.Context, in *AddCurrencyRequest, opts ...grpc.CallOption) (*AddCurrencyResponse, error)
	// Add a trading pair to the list of supported trading pairs.
	AddPair(ctx context.Context, in *AddPairRequest, opts ...grpc.CallOption) (*AddPairResponse, error)
	// Removes an order from the order book by its local id.
	RemoveOrder(ctx context.Context, in *RemoveOrderRequest, opts ...grpc.CallOption) (*RemoveOrderResponse, error)
	// Get the total balance available across all channels for a given currency.
	ChannelBalance(ctx context.Context, in *ChannelBalanceRequest, opts ...grpc.CallOption) (*ChannelBalanceResponse, error)
	// Connect to an XU node.
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	// Ban a XU node manually and disconnect from it.
	Ban(ctx context.Context, in *BanRequest, opts ...grpc.CallOption) (*BanResponse, error)
	// Get general information about this Exchange Union node.
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	// Gets orders from the order book. This call returns the state of the order book at a given point
	// in time, although it is not guaranteed to still be vaild by the time a response is received
	// and processed by a client. It accepts an optional trading pair id parameter. If specified, only
	// orders for that particular trading pair are returned. Otherwise, all orders are returned. Orders
	// are separated into buys and sells for each trading pair, but unsorted.
	GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error)
	// Get the list of the order book's supported currencies.
	ListCurrencies(ctx context.Context, in *ListCurrenciesRequest, opts ...grpc.CallOption) (*ListCurrenciesResponse, error)
	// Get the list of the order book's suported trading pairs.
	ListPairs(ctx context.Context, in *ListPairsRequest, opts ...grpc.CallOption) (*ListPairsResponse, error)
	// Get a list of connected peers.
	ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error)
	// Add an order to the order book.
	// If price is zero or unspecified a market order will get added.
	PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error)
	// Remove a currency.
	RemoveCurrency(ctx context.Context, in *RemoveCurrencyRequest, opts ...grpc.CallOption) (*RemoveCurrencyResponse, error)
	// Remove a trading pair.
	RemovePair(ctx context.Context, in *RemovePairRequest, opts ...grpc.CallOption) (*RemovePairResponse, error)
	// Begin shutting down xud.
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// Subscribes to orders being added to the order book. This call, together with SubscribeRemovedOrders,
	// allows the client to maintain an up-to-date view of the order book. For example, an exchange that
	// wants to show its users a real time list of the orders available to them would subscribe to this
	// streaming call to be alerted of new orders as they become available for trading.
	SubscribeAddedOrders(ctx context.Context, in *SubscribeAddedOrdersRequest, opts ...grpc.CallOption) (Xud_SubscribeAddedOrdersClient, error)
	// Subscribes to orders being removed - either in full or in part - from the order book. This call,
	// together with SubscribeAddedOrders, allows the client to maintain an up-to-date view of the order
	// book. For example, an exchange that wants to show its users a real time list of the orders available
	// to them would subscribe to this streaming call to be alerted when part or all of an existing order
	// is no longer available for trading.
	SubscribeRemovedOrders(ctx context.Context, in *SubscribeRemovedOrdersRequest, opts ...grpc.CallOption) (Xud_SubscribeRemovedOrdersClient, error)
	// Subscribes to completed swaps that are initiated by a remote peer. This call allows the client to
	// get real-time notifications when its orders are filled by a remote taker. It can be used for
	// tracking order executions, updating balances, and informing a trader when one of their orders
	// is settled through Exchange Union network.
	SubscribeSwaps(ctx context.Context, in *SubscribeSwapsRequest, opts ...grpc.CallOption) (Xud_SubscribeSwapsClient, error)
}

type xudClient struct {
	cc *grpc.ClientConn
}

func NewXudClient(cc *grpc.ClientConn) XudClient {
	return &xudClient{cc}
}

func (c *xudClient) AddCurrency(ctx context.Context, in *AddCurrencyRequest, opts ...grpc.CallOption) (*AddCurrencyResponse, error) {
	out := new(AddCurrencyResponse)
	err := grpc.Invoke(ctx, "/xudrpc.Xud/AddCurrency", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xudClient) AddPair(ctx context.Context, in *AddPairRequest, opts ...grpc.CallOption) (*AddPairResponse, error) {
	out := new(AddPairResponse)
	err := grpc.Invoke(ctx, "/xudrpc.Xud/AddPair", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xudClient) RemoveOrder(ctx context.Context, in *RemoveOrderRequest, opts ...grpc.CallOption) (*RemoveOrderResponse, error) {
	out := new(RemoveOrderResponse)
	err := grpc.Invoke(ctx, "/xudrpc.Xud/RemoveOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xudClient) ChannelBalance(ctx context.Context, in *ChannelBalanceRequest, opts ...grpc.CallOption) (*ChannelBalanceResponse, error) {
	out := new(ChannelBalanceResponse)
	err := grpc.Invoke(ctx, "/xudrpc.Xud/ChannelBalance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xudClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := grpc.Invoke(ctx, "/xudrpc.Xud/Connect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xudClient) Ban(ctx context.Context, in *BanRequest, opts ...grpc.CallOption) (*BanResponse, error) {
	out := new(BanResponse)
	err := grpc.Invoke(ctx, "/xudrpc.Xud/Ban", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xudClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := grpc.Invoke(ctx, "/xudrpc.Xud/GetInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xudClient) GetOrders(ctx context.Context, in *GetOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error) {
	out := new(GetOrdersResponse)
	err := grpc.Invoke(ctx, "/xudrpc.Xud/GetOrders", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xudClient) ListCurrencies(ctx context.Context, in *ListCurrenciesRequest, opts ...grpc.CallOption) (*ListCurrenciesResponse, error) {
	out := new(ListCurrenciesResponse)
	err := grpc.Invoke(ctx, "/xudrpc.Xud/ListCurrencies", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xudClient) ListPairs(ctx context.Context, in *ListPairsRequest, opts ...grpc.CallOption) (*ListPairsResponse, error) {
	out := new(ListPairsResponse)
	err := grpc.Invoke(ctx, "/xudrpc.Xud/ListPairs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xudClient) ListPeers(ctx context.Context, in *ListPeersRequest, opts ...grpc.CallOption) (*ListPeersResponse, error) {
	out := new(ListPeersResponse)
	err := grpc.Invoke(ctx, "/xudrpc.Xud/ListPeers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xudClient) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*PlaceOrderResponse, error) {
	out := new(PlaceOrderResponse)
	err := grpc.Invoke(ctx, "/xudrpc.Xud/PlaceOrder", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xudClient) RemoveCurrency(ctx context.Context, in *RemoveCurrencyRequest, opts ...grpc.CallOption) (*RemoveCurrencyResponse, error) {
	out := new(RemoveCurrencyResponse)
	err := grpc.Invoke(ctx, "/xudrpc.Xud/RemoveCurrency", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xudClient) RemovePair(ctx context.Context, in *RemovePairRequest, opts ...grpc.CallOption) (*RemovePairResponse, error) {
	out := new(RemovePairResponse)
	err := grpc.Invoke(ctx, "/xudrpc.Xud/RemovePair", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xudClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	out := new(ShutdownResponse)
	err := grpc.Invoke(ctx, "/xudrpc.Xud/Shutdown", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xudClient) SubscribeAddedOrders(ctx context.Context, in *SubscribeAddedOrdersRequest, opts ...grpc.CallOption) (Xud_SubscribeAddedOrdersClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Xud_serviceDesc.Streams[0], c.cc, "/xudrpc.Xud/SubscribeAddedOrders", opts...)
	if err != nil {
		return nil, err
	}
	x := &xudSubscribeAddedOrdersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Xud_SubscribeAddedOrdersClient interface {
	Recv() (*Order, error)
	grpc.ClientStream
}

type xudSubscribeAddedOrdersClient struct {
	grpc.ClientStream
}

func (x *xudSubscribeAddedOrdersClient) Recv() (*Order, error) {
	m := new(Order)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *xudClient) SubscribeRemovedOrders(ctx context.Context, in *SubscribeRemovedOrdersRequest, opts ...grpc.CallOption) (Xud_SubscribeRemovedOrdersClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Xud_serviceDesc.Streams[1], c.cc, "/xudrpc.Xud/SubscribeRemovedOrders", opts...)
	if err != nil {
		return nil, err
	}
	x := &xudSubscribeRemovedOrdersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Xud_SubscribeRemovedOrdersClient interface {
	Recv() (*OrderRemoval, error)
	grpc.ClientStream
}

type xudSubscribeRemovedOrdersClient struct {
	grpc.ClientStream
}

func (x *xudSubscribeRemovedOrdersClient) Recv() (*OrderRemoval, error) {
	m := new(OrderRemoval)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *xudClient) SubscribeSwaps(ctx context.Context, in *SubscribeSwapsRequest, opts ...grpc.CallOption) (Xud_SubscribeSwapsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Xud_serviceDesc.Streams[2], c.cc, "/xudrpc.Xud/SubscribeSwaps", opts...)
	if err != nil {
		return nil, err
	}
	x := &xudSubscribeSwapsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Xud_SubscribeSwapsClient interface {
	Recv() (*SwapResult, error)
	grpc.ClientStream
}

type xudSubscribeSwapsClient struct {
	grpc.ClientStream
}

func (x *xudSubscribeSwapsClient) Recv() (*SwapResult, error) {
	m := new(SwapResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Xud service

type XudServer interface {
	// Add a currency to the list of supported currencies.
	AddCurrency(context.Context, *AddCurrencyRequest) (*AddCurrencyResponse, error)
	// Add a trading pair to the list of supported trading pairs.
	AddPair(context.Context, *AddPairRequest) (*AddPairResponse, error)
	// Removes an order from the order book by its local id.
	RemoveOrder(context.Context, *RemoveOrderRequest) (*RemoveOrderResponse, error)
	// Get the total balance available across all channels for a given currency.
	ChannelBalance(context.Context, *ChannelBalanceRequest) (*ChannelBalanceResponse, error)
	// Connect to an XU node.
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	// Ban a XU node manually and disconnect from it.
	Ban(context.Context, *BanRequest) (*BanResponse, error)
	// Get general information about this Exchange Union node.
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	// Gets orders from the order book. This call returns the state of the order book at a given point
	// in time, although it is not guaranteed to still be vaild by the time a response is received
	// and processed by a client. It accepts an optional trading pair id parameter. If specified, only
	// orders for that particular trading pair are returned. Otherwise, all orders are returned. Orders
	// are separated into buys and sells for each trading pair, but unsorted.
	GetOrders(context.Context, *GetOrdersRequest) (*GetOrdersResponse, error)
	// Get the list of the order book's supported currencies.
	ListCurrencies(context.Context, *ListCurrenciesRequest) (*ListCurrenciesResponse, error)
	// Get the list of the order book's suported trading pairs.
	ListPairs(context.Context, *ListPairsRequest) (*ListPairsResponse, error)
	// Get a list of connected peers.
	ListPeers(context.Context, *ListPeersRequest) (*ListPeersResponse, error)
	// Add an order to the order book.
	// If price is zero or unspecified a market order will get added.
	PlaceOrder(context.Context, *PlaceOrderRequest) (*PlaceOrderResponse, error)
	// Remove a currency.
	RemoveCurrency(context.Context, *RemoveCurrencyRequest) (*RemoveCurrencyResponse, error)
	// Remove a trading pair.
	RemovePair(context.Context, *RemovePairRequest) (*RemovePairResponse, error)
	// Begin shutting down xud.
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// Subscribes to orders being added to the order book. This call, together with SubscribeRemovedOrders,
	// allows the client to maintain an up-to-date view of the order book. For example, an exchange that
	// wants to show its users a real time list of the orders available to them would subscribe to this
	// streaming call to be alerted of new orders as they become available for trading.
	SubscribeAddedOrders(*SubscribeAddedOrdersRequest, Xud_SubscribeAddedOrdersServer) error
	// Subscribes to orders being removed - either in full or in part - from the order book. This call,
	// together with SubscribeAddedOrders, allows the client to maintain an up-to-date view of the order
	// book. For example, an exchange that wants to show its users a real time list of the orders available
	// to them would subscribe to this streaming call to be alerted when part or all of an existing order
	// is no longer available for trading.
	SubscribeRemovedOrders(*SubscribeRemovedOrdersRequest, Xud_SubscribeRemovedOrdersServer) error
	// Subscribes to completed swaps that are initiated by a remote peer. This call allows the client to
	// get real-time notifications when its orders are filled by a remote taker. It can be used for
	// tracking order executions, updating balances, and informing a trader when one of their orders
	// is settled through Exchange Union network.
	SubscribeSwaps(*SubscribeSwapsRequest, Xud_SubscribeSwapsServer) error
}

func RegisterXudServer(s *grpc.Server, srv XudServer) {
	s.RegisterService(&_Xud_serviceDesc, srv)
}

func _Xud_AddCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XudServer).AddCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xudrpc.Xud/AddCurrency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XudServer).AddCurrency(ctx, req.(*AddCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xud_AddPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XudServer).AddPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xudrpc.Xud/AddPair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XudServer).AddPair(ctx, req.(*AddPairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xud_RemoveOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XudServer).RemoveOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xudrpc.Xud/RemoveOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XudServer).RemoveOrder(ctx, req.(*RemoveOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xud_ChannelBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XudServer).ChannelBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xudrpc.Xud/ChannelBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XudServer).ChannelBalance(ctx, req.(*ChannelBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xud_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XudServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xudrpc.Xud/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XudServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xud_Ban_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XudServer).Ban(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xudrpc.Xud/Ban",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XudServer).Ban(ctx, req.(*BanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xud_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XudServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xudrpc.Xud/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XudServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xud_GetOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XudServer).GetOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xudrpc.Xud/GetOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XudServer).GetOrders(ctx, req.(*GetOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xud_ListCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XudServer).ListCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xudrpc.Xud/ListCurrencies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XudServer).ListCurrencies(ctx, req.(*ListCurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xud_ListPairs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPairsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XudServer).ListPairs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xudrpc.Xud/ListPairs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XudServer).ListPairs(ctx, req.(*ListPairsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xud_ListPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XudServer).ListPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xudrpc.Xud/ListPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XudServer).ListPeers(ctx, req.(*ListPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xud_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XudServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xudrpc.Xud/PlaceOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XudServer).PlaceOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xud_RemoveCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XudServer).RemoveCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xudrpc.Xud/RemoveCurrency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XudServer).RemoveCurrency(ctx, req.(*RemoveCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xud_RemovePair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XudServer).RemovePair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xudrpc.Xud/RemovePair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XudServer).RemovePair(ctx, req.(*RemovePairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xud_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XudServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/xudrpc.Xud/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XudServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Xud_SubscribeAddedOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeAddedOrdersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(XudServer).SubscribeAddedOrders(m, &xudSubscribeAddedOrdersServer{stream})
}

type Xud_SubscribeAddedOrdersServer interface {
	Send(*Order) error
	grpc.ServerStream
}

type xudSubscribeAddedOrdersServer struct {
	grpc.ServerStream
}

func (x *xudSubscribeAddedOrdersServer) Send(m *Order) error {
	return x.ServerStream.SendMsg(m)
}

func _Xud_SubscribeRemovedOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRemovedOrdersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(XudServer).SubscribeRemovedOrders(m, &xudSubscribeRemovedOrdersServer{stream})
}

type Xud_SubscribeRemovedOrdersServer interface {
	Send(*OrderRemoval) error
	grpc.ServerStream
}

type xudSubscribeRemovedOrdersServer struct {
	grpc.ServerStream
}

func (x *xudSubscribeRemovedOrdersServer) Send(m *OrderRemoval) error {
	return x.ServerStream.SendMsg(m)
}

func _Xud_SubscribeSwaps_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeSwapsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(XudServer).SubscribeSwaps(m, &xudSubscribeSwapsServer{stream})
}

type Xud_SubscribeSwapsServer interface {
	Send(*SwapResult) error
	grpc.ServerStream
}

type xudSubscribeSwapsServer struct {
	grpc.ServerStream
}

func (x *xudSubscribeSwapsServer) Send(m *SwapResult) error {
	return x.ServerStream.SendMsg(m)
}

var _Xud_serviceDesc = grpc.ServiceDesc{
	ServiceName: "xudrpc.Xud",
	HandlerType: (*XudServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddCurrency",
			Handler:    _Xud_AddCurrency_Handler,
		},
		{
			MethodName: "AddPair",
			Handler:    _Xud_AddPair_Handler,
		},
		{
			MethodName: "RemoveOrder",
			Handler:    _Xud_RemoveOrder_Handler,
		},
		{
			MethodName: "ChannelBalance",
			Handler:    _Xud_ChannelBalance_Handler,
		},
		{
			MethodName: "Connect",
			Handler:    _Xud_Connect_Handler,
		},
		{
			MethodName: "Ban",
			Handler:    _Xud_Ban_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _Xud_GetInfo_Handler,
		},
		{
			MethodName: "GetOrders",
			Handler:    _Xud_GetOrders_Handler,
		},
		{
			MethodName: "ListCurrencies",
			Handler:    _Xud_ListCurrencies_Handler,
		},
		{
			MethodName: "ListPairs",
			Handler:    _Xud_ListPairs_Handler,
		},
		{
			MethodName: "ListPeers",
			Handler:    _Xud_ListPeers_Handler,
		},
		{
			MethodName: "PlaceOrder",
			Handler:    _Xud_PlaceOrder_Handler,
		},
		{
			MethodName: "RemoveCurrency",
			Handler:    _Xud_RemoveCurrency_Handler,
		},
		{
			MethodName: "RemovePair",
			Handler:    _Xud_RemovePair_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _Xud_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeAddedOrders",
			Handler:       _Xud_SubscribeAddedOrders_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeRemovedOrders",
			Handler:       _Xud_SubscribeRemovedOrders_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeSwaps",
			Handler:       _Xud_SubscribeSwaps_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "xudrpc.proto",
}

func init() { proto.RegisterFile("xudrpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2001 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x49, 0x73, 0x24, 0x47,
	0x15, 0x9e, 0xea, 0xbd, 0x5f, 0x4b, 0xad, 0xee, 0x94, 0xd4, 0xea, 0xe9, 0x59, 0x10, 0xe9, 0x19,
	0x10, 0x63, 0x59, 0x1a, 0x34, 0x07, 0x3b, 0x1c, 0xc1, 0x41, 0x92, 0x87, 0x61, 0x02, 0xd9, 0x38,
	0x4a, 0xc6, 0x01, 0x01, 0x31, 0x15, 0xd5, 0x55, 0x89, 0xba, 0x42, 0xa5, 0xac, 0x9e, 0x5a, 0x24,
	0x4f, 0x70, 0xe3, 0x2f, 0x70, 0xe1, 0x42, 0x04, 0x70, 0xe3, 0xc6, 0x85, 0x3f, 0xc1, 0x81, 0x0b,
	0x7f, 0x81, 0x13, 0xbf, 0x82, 0xc8, 0xad, 0x32, 0xb3, 0xab, 0xda, 0x98, 0x08, 0xdf, 0xea, 0x2d,
	0xf9, 0xe5, 0xcb, 0x97, 0x6f, 0xc9, 0x57, 0xb0, 0xf1, 0x55, 0x11, 0xa6, 0xcb, 0xe0, 0x68, 0x99,
	0x26, 0x79, 0x82, 0x3a, 0x82, 0x9a, 0x3d, 0xbc, 0x4a, 0x92, 0xab, 0x98, 0x1c, 0xfb, 0xcb, 0xe8,
	0xd8, 0xa7, 0x34, 0xc9, 0xfd, 0x3c, 0x4a, 0x68, 0x26, 0xb4, 0xf0, 0x7f, 0x1c, 0x40, 0xa7, 0x61,
	0x78, 0x5e, 0xa4, 0x29, 0xa1, 0xc1, 0x3b, 0x97, 0xbc, 0x2d, 0x48, 0x96, 0xa3, 0x19, 0xf4, 0x02,
	0xc9, 0x9a, 0x3a, 0xfb, 0xce, 0x41, 0xdf, 0x2d, 0x69, 0xf4, 0x0a, 0x06, 0xd9, 0x9d, 0xbf, 0xf4,
	0x82, 0x38, 0x22, 0x34, 0x9f, 0x36, 0xf6, 0x9d, 0x83, 0xe1, 0xc9, 0xd3, 0x23, 0xb9, 0x79, 0x15,
	0xec, 0xe8, 0xf2, 0xce, 0x5f, 0x9e, 0x73, 0x65, 0xd7, 0x5c, 0x89, 0x9e, 0xc0, 0x66, 0x9e, 0x5c,
	0x13, 0xea, 0xf9, 0x61, 0x98, 0x92, 0x2c, 0x9b, 0x36, 0xf9, 0x4e, 0x36, 0x13, 0x7d, 0x0f, 0x86,
	0x21, 0x09, 0xa2, 0x1b, 0x3f, 0xf6, 0x96, 0xb1, 0x1f, 0x90, 0x6c, 0xda, 0xda, 0x77, 0x0e, 0x36,
	0xdd, 0x15, 0x2e, 0xfe, 0x2e, 0x80, 0xde, 0x08, 0x75, 0xa1, 0x79, 0xf1, 0xd9, 0x27, 0xa3, 0x7b,
	0x08, 0xa0, 0xe3, 0x9e, 0xbe, 0xfe, 0xe4, 0xe5, 0x67, 0x23, 0x07, 0xef, 0xc2, 0xb6, 0x65, 0x5e,
	0xb6, 0x4c, 0x68, 0x46, 0xf0, 0x1b, 0x18, 0x9e, 0x86, 0xe1, 0xe7, 0x7e, 0x94, 0xaa, 0xe3, 0x3f,
	0x81, 0xcd, 0xb9, 0x9f, 0x11, 0x6f, 0xc5, 0x07, 0x36, 0x93, 0x59, 0xf6, 0xb6, 0x48, 0x72, 0x43,
	0xad, 0xc1, 0xd5, 0x56, 0xb8, 0x78, 0x0c, 0x5b, 0x25, 0xbe, 0xdc, 0xf2, 0x39, 0x20, 0x97, 0xdc,
	0x24, 0xb7, 0xe4, 0x67, 0x69, 0x48, 0x52, 0xc3, 0xeb, 0x09, 0xa3, 0xbd, 0x28, 0x54, 0x5e, 0x57,
	0x34, 0xb3, 0xdd, 0x5a, 0xa1, 0x6d, 0x3f, 0x5f, 0xf8, 0x94, 0x92, 0xf8, 0xcc, 0x8f, 0x7d, 0x1a,
	0x10, 0x34, 0x85, 0xee, 0x5c, 0x7c, 0x72, 0x8c, 0xa6, 0xab, 0x48, 0x74, 0x02, 0x3b, 0x4b, 0x42,
	0xc3, 0x88, 0x5e, 0x79, 0xc9, 0x92, 0x50, 0x4f, 0xa9, 0x35, 0xb8, 0x5a, 0xad, 0x0c, 0xbf, 0x80,
	0x5d, 0x1b, 0xff, 0x1b, 0x44, 0x08, 0xfe, 0xbb, 0x03, 0x93, 0xd5, 0x55, 0xc2, 0x5e, 0xf4, 0x63,
	0xe8, 0x49, 0xe8, 0x6c, 0xea, 0xec, 0x37, 0x0f, 0x06, 0x27, 0x87, 0x2a, 0x72, 0xea, 0x57, 0x1c,
	0x49, 0x3a, 0x7b, 0x49, 0xf3, 0xf4, 0x9d, 0xdb, 0xe1, 0x0e, 0xc9, 0x66, 0x97, 0xb0, 0x69, 0x09,
	0xd0, 0x08, 0x9a, 0xd7, 0x44, 0x99, 0xc2, 0x3e, 0xd1, 0x21, 0xb4, 0x6f, 0xfd, 0xb8, 0x10, 0xe7,
	0x1b, 0x9c, 0x4c, 0xd6, 0xec, 0x23, 0x94, 0x3e, 0x6e, 0x7c, 0xe4, 0xe0, 0x43, 0x18, 0x9e, 0x27,
	0x94, 0x92, 0x20, 0x37, 0x4e, 0x49, 0x93, 0x90, 0x78, 0x45, 0x1a, 0xa9, 0x53, 0x2a, 0x9a, 0x5d,
	0x6b, 0xa9, 0x5d, 0x5e, 0x2b, 0x9c, 0xf9, 0x54, 0x2d, 0xc6, 0xb0, 0xc1, 0x95, 0x97, 0xc5, 0xdc,
	0xd3, 0xb6, 0x59, 0x3c, 0xbc, 0x09, 0x03, 0xbe, 0x42, 0x02, 0x8c, 0x60, 0xf8, 0x8a, 0xe4, 0xaf,
	0xe9, 0x6f, 0x12, 0x09, 0x82, 0xff, 0xd1, 0x80, 0xad, 0x92, 0x25, 0x9d, 0x38, 0x85, 0xee, 0x2d,
	0x49, 0xb3, 0x28, 0xa1, 0x12, 0x53, 0x91, 0x95, 0x2d, 0x1b, 0xd5, 0x2d, 0x11, 0x82, 0x56, 0x91,
	0x46, 0x2c, 0xdb, 0x9a, 0x07, 0x7d, 0x97, 0x7f, 0xa3, 0x87, 0xd0, 0xa7, 0xc5, 0x8d, 0xb7, 0x24,
	0x24, 0x15, 0xf9, 0xd5, 0x76, 0x35, 0xa3, 0x94, 0xfa, 0x51, 0x9a, 0x4d, 0xdb, 0x86, 0x94, 0x31,
	0xd0, 0xfb, 0x20, 0x2f, 0x65, 0xda, 0xe1, 0x8e, 0xde, 0x56, 0x8e, 0xe6, 0x91, 0x9a, 0x9d, 0x27,
	0x05, 0xcd, 0xd5, 0xbd, 0xa1, 0xef, 0x43, 0x27, 0xa6, 0xe1, 0x3c, 0x0f, 0xa6, 0x5d, 0xae, 0xbc,
	0xa5, 0x94, 0x2f, 0x68, 0xc8, 0xcf, 0x28, 0xc5, 0x52, 0x31, 0xce, 0x83, 0x69, 0x6f, 0xbd, 0x62,
	0x9c, 0x07, 0xe8, 0x19, 0x74, 0x52, 0x3f, 0x0a, 0x09, 0x9d, 0xf6, 0xb9, 0x22, 0x52, 0x8a, 0x2e,
	0xe7, 0x0a, 0x5d, 0xa1, 0x81, 0x7f, 0x0d, 0xa3, 0x57, 0x24, 0x17, 0x76, 0xa9, 0x5b, 0x9a, 0x42,
	0x97, 0x9d, 0x43, 0xe7, 0x9c, 0x22, 0xd1, 0x11, 0xa0, 0x88, 0x06, 0x71, 0x11, 0x12, 0x2f, 0xb9,
	0xa3, 0x9e, 0x3c, 0x24, 0x73, 0x69, 0xcf, 0xad, 0x91, 0xe0, 0x3f, 0x3a, 0x30, 0x36, 0xe0, 0xe5,
	0x65, 0xfd, 0xa8, 0x74, 0x8f, 0x88, 0xf7, 0xb2, 0x52, 0x56, 0x54, 0xa5, 0xc3, 0xec, 0x40, 0x7f,
	0x0d, 0x03, 0x83, 0x5d, 0x13, 0xe6, 0x4f, 0xec, 0x30, 0x1f, 0xda, 0xde, 0x37, 0xc3, 0x7b, 0x0f,
	0x76, 0x2f, 0xa2, 0x2c, 0x97, 0xf5, 0x2f, 0x22, 0xca, 0x05, 0xf8, 0x23, 0x98, 0xac, 0x0a, 0xa4,
	0xf1, 0x8f, 0x01, 0x82, 0x92, 0xcb, 0x0f, 0xd0, 0x77, 0x0d, 0x0e, 0x46, 0x30, 0x62, 0x2b, 0x59,
	0x6d, 0x2b, 0xd1, 0x7e, 0x00, 0x63, 0x83, 0x27, 0x81, 0x76, 0xa0, 0x2d, 0xc2, 0x47, 0x60, 0x08,
	0xa2, 0x5c, 0x4e, 0xf4, 0x7d, 0xe0, 0x0f, 0xe5, 0x72, 0x62, 0x3a, 0x11, 0x43, 0x5b, 0xc4, 0xa6,
	0xf0, 0xe1, 0x86, 0x3a, 0x24, 0xd3, 0x72, 0x85, 0x08, 0xff, 0x0a, 0x06, 0x17, 0x34, 0x94, 0xd9,
	0x9d, 0xa1, 0x09, 0x74, 0xfc, 0x20, 0x8f, 0x6e, 0x45, 0x19, 0x6c, 0xbb, 0x92, 0x62, 0x29, 0x1d,
	0x51, 0x29, 0x69, 0x70, 0x49, 0x49, 0xf3, 0x58, 0x10, 0x55, 0x90, 0xf7, 0xa2, 0xb6, 0xab, 0x48,
	0xfc, 0x4f, 0x07, 0xba, 0x32, 0xf2, 0xd8, 0x59, 0x48, 0x9a, 0x26, 0xa9, 0xbc, 0x05, 0x41, 0xa0,
	0x63, 0xe8, 0x05, 0x72, 0x6f, 0x79, 0x15, 0xdb, 0x46, 0xc8, 0x2a, 0xb3, 0xdc, 0x52, 0x89, 0x19,
	0x18, 0x2c, 0xfc, 0x88, 0xaa, 0x4c, 0x94, 0x14, 0xda, 0x87, 0xc1, 0x3c, 0x4e, 0x82, 0xeb, 0x05,
	0x89, 0xae, 0x16, 0xb9, 0xcc, 0x46, 0x93, 0x55, 0x66, 0x70, 0xdb, 0xc8, 0x60, 0xa3, 0x26, 0x74,
	0xec, 0x9a, 0xb0, 0x03, 0x6d, 0x3f, 0x8e, 0xfc, 0x8c, 0x67, 0x5c, 0xdf, 0x15, 0x04, 0xfe, 0x73,
	0x03, 0xda, 0x3c, 0x44, 0xf8, 0xd5, 0xa4, 0x91, 0x6c, 0x17, 0x8e, 0x2b, 0x08, 0xe6, 0xa6, 0xb7,
	0x85, 0x4f, 0xf3, 0x28, 0x17, 0x55, 0xc4, 0x71, 0x4b, 0xda, 0x4c, 0x99, 0xa6, 0x9d, 0x32, 0x43,
	0x68, 0x44, 0x21, 0x37, 0xb9, 0xef, 0x36, 0xa2, 0x10, 0x3d, 0x81, 0x0d, 0x76, 0x39, 0x65, 0x3d,
	0x62, 0xc5, 0xa3, 0xff, 0x93, 0x7b, 0xae, 0xc5, 0x45, 0x0f, 0xa1, 0x17, 0x27, 0x81, 0x1f, 0x33,
	0xc0, 0x8e, 0xd4, 0x28, 0x39, 0x3c, 0x06, 0x53, 0xe2, 0xe7, 0x24, 0xf4, 0xfc, 0x9c, 0x1f, 0xa2,
	0xe9, 0x1a, 0x1c, 0xf4, 0x14, 0x5a, 0x59, 0x14, 0x12, 0x5e, 0x27, 0x86, 0x27, 0x63, 0x2b, 0xfe,
	0x2f, 0xa3, 0x90, 0xb8, 0x5c, 0xcc, 0x4a, 0x63, 0x94, 0xe9, 0x74, 0xe5, 0xd5, 0xa2, 0xe7, 0x5a,
	0xbc, 0xb3, 0x4d, 0x18, 0x08, 0x82, 0x17, 0x3e, 0xfc, 0x27, 0x07, 0x36, 0x64, 0xbb, 0xbd, 0x49,
	0x6e, 0xfd, 0xd8, 0x72, 0x8a, 0xb3, 0xde, 0x29, 0x0d, 0xdb, 0x29, 0x66, 0x5b, 0x6f, 0xda, 0x6d,
	0x9d, 0xc9, 0xca, 0xa3, 0x0b, 0xb7, 0xe9, 0x83, 0xaf, 0x5a, 0xdc, 0xae, 0x5a, 0x8c, 0x17, 0xd0,
	0x11, 0x89, 0x8e, 0x3e, 0x00, 0x98, 0x17, 0xef, 0x3c, 0xab, 0xd6, 0x6c, 0x5a, 0xce, 0x70, 0x0d,
	0x05, 0x74, 0x0c, 0x83, 0x8c, 0xc4, 0xb1, 0xae, 0x6a, 0x35, 0xfa, 0xa6, 0x06, 0xfe, 0x12, 0x80,
	0x73, 0x3f, 0xf5, 0xf3, 0x60, 0x81, 0xde, 0x83, 0xf6, 0x8d, 0x7f, 0x4d, 0x44, 0x0e, 0x54, 0x16,
	0x0a, 0x19, 0x53, 0xca, 0xb9, 0x52, 0xa3, 0x56, 0x89, 0xcb, 0xf0, 0x0b, 0x55, 0xe0, 0x78, 0xa3,
	0x60, 0xb1, 0xcd, 0x7c, 0x2f, 0x93, 0x96, 0x7f, 0xb3, 0xa2, 0x97, 0xdc, 0x51, 0x99, 0xad, 0xec,
	0x13, 0xff, 0xa1, 0x01, 0x2d, 0x96, 0xfb, 0xcc, 0xeb, 0xea, 0xf5, 0x28, 0xab, 0xb7, 0x7a, 0x37,
	0x7e, 0x93, 0x56, 0x78, 0x00, 0x5b, 0x31, 0x0d, 0xbd, 0x79, 0x1e, 0x94, 0x6a, 0xe2, 0x82, 0x56,
	0xd9, 0x4a, 0x33, 0x36, 0x34, 0x5b, 0x5a, 0xd3, 0x60, 0x33, 0x8b, 0x22, 0x3a, 0x4f, 0x0a, 0x1a,
	0xca, 0x0b, 0x53, 0xa4, 0xae, 0x81, 0x1d, 0xa3, 0x06, 0xb2, 0x74, 0xff, 0xaa, 0x08, 0x3d, 0x95,
	0xbc, 0x22, 0x49, 0x4d, 0x16, 0x3a, 0x84, 0x71, 0x46, 0x82, 0x84, 0x86, 0x99, 0x17, 0x88, 0x07,
	0x07, 0x09, 0x79, 0xb4, 0xb7, 0xdd, 0xaa, 0x00, 0xff, 0xc5, 0x81, 0xf1, 0xe7, 0xec, 0x49, 0x6c,
	0x3d, 0x2d, 0xbf, 0xcd, 0x24, 0x37, 0xe3, 0xb9, 0xb5, 0x12, 0xcf, 0x2a, 0x19, 0xdb, 0x5f, 0x9b,
	0x8c, 0xf8, 0xb7, 0x80, 0x4c, 0x1b, 0x65, 0x95, 0x3f, 0x84, 0xee, 0x0d, 0x8b, 0xae, 0xf2, 0x6d,
	0x88, 0xac, 0xf5, 0x3c, 0xf2, 0x5c, 0xa5, 0x82, 0x3e, 0x84, 0xad, 0x94, 0xdc, 0xf8, 0x11, 0xe5,
	0x8f, 0x56, 0x9e, 0x21, 0xb5, 0x71, 0xb6, 0xaa, 0x85, 0x53, 0x00, 0xfd, 0x36, 0x58, 0x53, 0xcd,
	0x8d, 0xb8, 0x6a, 0xd8, 0x71, 0x35, 0x33, 0xea, 0xbc, 0x68, 0x12, 0xba, 0xa4, 0x1b, 0x45, 0xb8,
	0x65, 0x15, 0x61, 0xf6, 0x8e, 0x16, 0xcf, 0xf7, 0xff, 0x63, 0xd2, 0xc2, 0x53, 0x98, 0xac, 0x2e,
	0x92, 0xef, 0xc4, 0x0f, 0x60, 0x2c, 0x24, 0xe6, 0xd4, 0xb2, 0xf6, 0x25, 0x83, 0x77, 0xd4, 0xb8,
	0x61, 0x0d, 0x21, 0x63, 0xd8, 0xba, 0x5c, 0x14, 0x79, 0x98, 0xdc, 0xa9, 0x27, 0x2b, 0x6b, 0xc8,
	0x9a, 0x25, 0xd5, 0x1e, 0xc1, 0x83, 0xcb, 0x62, 0x9e, 0x05, 0x69, 0x34, 0x27, 0xa7, 0x61, 0x48,
	0x42, 0xeb, 0xfd, 0x84, 0xbf, 0x03, 0x8f, 0x4a, 0xb1, 0xd8, 0x64, 0x45, 0x61, 0x0f, 0x76, 0x4b,
	0x05, 0x36, 0xa1, 0x95, 0x82, 0xbf, 0x35, 0xc4, 0xc8, 0xe6, 0x92, 0xac, 0x88, 0x73, 0x74, 0xbf,
	0x32, 0xfd, 0x74, 0x39, 0xfd, 0xda, 0xae, 0x92, 0x8d, 0x95, 0x2a, 0xb9, 0x3e, 0x4e, 0x27, 0xd0,
	0x49, 0xbd, 0x85, 0x9f, 0x2d, 0xe4, 0x65, 0x48, 0x8a, 0xe5, 0xb2, 0x7f, 0xc3, 0x8a, 0x8d, 0x97,
	0x92, 0x80, 0x44, 0xb7, 0x44, 0x64, 0x6a, 0xd3, 0x5d, 0x65, 0xb3, 0xdc, 0x94, 0xac, 0x8c, 0x8d,
	0xba, 0x1d, 0xae, 0x65, 0xb2, 0x58, 0x95, 0xb1, 0x1a, 0x9c, 0x48, 0x5f, 0xbb, 0xbd, 0xbd, 0x0f,
	0xad, 0x34, 0x89, 0x55, 0x83, 0xda, 0x53, 0xd1, 0xa9, 0x8f, 0x7e, 0xe4, 0x26, 0x31, 0x71, 0xb9,
	0x12, 0x7e, 0x08, 0x2d, 0x46, 0xa1, 0x3e, 0xb4, 0xbf, 0x38, 0xfd, 0xe9, 0x4b, 0x77, 0x74, 0x8f,
	0x7d, 0x7e, 0xca, 0x3f, 0x9d, 0x67, 0x8f, 0xa1, 0x5f, 0xa6, 0x12, 0x9b, 0x71, 0xcf, 0x7e, 0xfe,
	0xcb, 0xd1, 0x3d, 0xd4, 0x83, 0xd6, 0xe5, 0xcb, 0x8b, 0x8b, 0x91, 0x73, 0xf2, 0xd7, 0x4d, 0x68,
	0xfe, 0xa2, 0x08, 0xd1, 0x1c, 0x06, 0xc6, 0xa4, 0x8b, 0x66, 0xeb, 0xa7, 0xf3, 0xd9, 0x83, 0x5a,
	0x99, 0xbc, 0xfb, 0xd9, 0xef, 0xfe, 0xf5, 0xef, 0xdf, 0x37, 0x76, 0xf0, 0xd6, 0xf1, 0xed, 0x0f,
	0x8f, 0xfd, 0x30, 0x54, 0xa1, 0xf9, 0xb1, 0xf3, 0x0c, 0xb9, 0xd0, 0x95, 0x63, 0x2d, 0x9a, 0x18,
	0x18, 0x46, 0x44, 0xce, 0xf6, 0x2a, 0x7c, 0x89, 0x3b, 0xe1, 0xb8, 0x23, 0x3c, 0x90, 0xb8, 0xec,
	0xca, 0x18, 0xe6, 0x1c, 0x06, 0xc6, 0x94, 0xab, 0xed, 0xae, 0x0e, 0xcb, 0xda, 0xee, 0xba, 0xb1,
	0xd8, 0xb2, 0x3b, 0xe5, 0x0a, 0x3c, 0x96, 0xd8, 0x1e, 0xd7, 0x95, 0x91, 0xf9, 0xd1, 0xba, 0x11,
	0x54, 0xec, 0xf4, 0xf8, 0xeb, 0x27, 0x54, 0xb5, 0x19, 0x42, 0x6c, 0x33, 0x59, 0x0b, 0xd4, 0xcc,
	0xed, 0x42, 0x57, 0x0e, 0x89, 0xda, 0x49, 0xf6, 0x8c, 0xa9, 0x9d, 0xb4, 0x3a, 0x4d, 0x5a, 0x4e,
	0x92, 0x05, 0x9e, 0x1d, 0xe0, 0x0c, 0x9a, 0x67, 0x3e, 0x45, 0x65, 0x71, 0xd4, 0x23, 0xe7, 0x6c,
	0xdb, 0xe2, 0x49, 0x1c, 0xc4, 0x71, 0x36, 0x70, 0x97, 0xe1, 0xcc, 0x7d, 0xca, 0x30, 0x2e, 0xa0,
	0x2b, 0xa7, 0x4a, 0x6d, 0x97, 0x3d, 0x79, 0x6a, 0xbb, 0x56, 0xc6, 0x4f, 0x3c, 0xe2, 0x78, 0x80,
	0x7a, 0x0c, 0x2f, 0x62, 0x10, 0x5f, 0x40, 0xbf, 0x9c, 0x66, 0xd0, 0xb4, 0x66, 0xc0, 0x11, 0x88,
	0xf7, 0xd7, 0x8e, 0x3e, 0xca, 0x46, 0x04, 0x0c, 0x53, 0x3e, 0x51, 0xae, 0x60, 0x68, 0x8f, 0x25,
	0xfa, 0xa2, 0x6a, 0xe7, 0x18, 0x7d, 0x51, 0xf5, 0xd3, 0x8c, 0x72, 0x28, 0x1a, 0x72, 0x87, 0x6a,
	0xd8, 0x4b, 0xe8, 0x97, 0x13, 0x8b, 0x36, 0x7f, 0x75, 0xb0, 0xd1, 0xe6, 0x57, 0xc6, 0x1b, 0x3c,
	0xe6, 0xc8, 0x03, 0xd4, 0x67, 0xc8, 0xa2, 0xaf, 0x2b, 0x50, 0x42, 0x2a, 0xa0, 0x84, 0xac, 0x03,
	0x35, 0x87, 0x9e, 0x15, 0x50, 0x8e, 0xf3, 0x06, 0x40, 0xf7, 0x4d, 0x54, 0xae, 0xad, 0xf4, 0xfb,
	0xd9, 0xac, 0x4e, 0x24, 0x71, 0xef, 0x73, 0xdc, 0x6d, 0xcc, 0xdd, 0xc0, 0xff, 0x9e, 0x95, 0xb9,
	0x41, 0x61, 0x68, 0x77, 0x1c, 0xed, 0xf2, 0xda, 0xf6, 0xa5, 0x5d, 0xbe, 0xa6, 0x51, 0x3d, 0xe2,
	0x7b, 0xed, 0x61, 0xa4, 0x13, 0xd1, 0xac, 0x21, 0x6f, 0x00, 0x74, 0x63, 0xd2, 0xe7, 0xa9, 0xf4,
	0xb6, 0xd9, 0xac, 0x4e, 0x54, 0x77, 0x1e, 0xb1, 0x87, 0xaa, 0x27, 0x5f, 0x42, 0x4f, 0xf5, 0x33,
	0xa4, 0x0b, 0xaf, 0xdd, 0xf4, 0x66, 0xd3, 0xaa, 0x40, 0x22, 0xef, 0x71, 0xe4, 0x31, 0xde, 0x60,
	0xc8, 0x99, 0x94, 0x32, 0xdc, 0x08, 0x76, 0xea, 0x7a, 0x22, 0x7a, 0xaf, 0x84, 0x5a, 0xdf, 0x31,
	0x67, 0xf6, 0xfb, 0x04, 0x3f, 0xe0, 0x9b, 0xec, 0xa2, 0x6d, 0xbe, 0x89, 0x5a, 0x27, 0x72, 0xe0,
	0xb9, 0x83, 0x72, 0x98, 0xd4, 0xf7, 0x57, 0xf4, 0xb4, 0xb2, 0x59, 0x5d, 0xff, 0x9d, 0xed, 0xd8,
	0xcf, 0x21, 0x31, 0xca, 0xfc, 0xaf, 0x5d, 0x7d, 0x18, 0xda, 0x4d, 0x5b, 0x07, 0x42, 0x6d, 0x33,
	0x9f, 0xa1, 0x6a, 0x5b, 0xb3, 0x0b, 0x63, 0xb9, 0x47, 0xc6, 0x96, 0x3d, 0x77, 0xe6, 0x1d, 0xfe,
	0x07, 0xfa, 0xc5, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x1e, 0x0d, 0x85, 0xb7, 0x16, 0x00,
	0x00,
}
