apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: bitcoin
  name: bitcoin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}