apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: litecoin
  name: litecoin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}